var cbs = require('./callbacks');

exports.map = {
  PLAYER_ID: {name:false, keep:true},
  PLAYER: {name:false, keep: true},
  FIRST_NAME: {name:false},
  LAST_NAME: {name:false},
  TEAM_ABBREVIATION: {name:false, keep: true},
  GP: {name:false, keep:true},
  MIN: {name:false, keep: true},
  DVS: {name:false},
  DPP: {name:false},
  DTP: {name:false},
  FG_PCT: {name:false},
  PTS_48: {name:false},
  DPP_TOT: {name: 'Points on Drives', cat: 'MSC', posneg:'POS'},
  DVS_TOT: {name:false},
  PASS: {name: 'Passes', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  AST: {name:false},
  AST_FT: {name:'Freethrow Assists', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  AST_SEC: {name:'Secondary Assists', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  AST_POT: {name:'Assist Opportunities', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  PTS_CRT: {name: 'Points Created By Assist', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  PTS_CRT_48: {name:false},
  AST_TOT: {name:'Assists', cat: 'PSS', posneg: 'POS'},
  TCH: {name:false},
  FC_TCH: {name:'Front Court Touches', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  TOP: {name:false},
  CL_TCH: {name:'Close Touches', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  EL_TCH: {name:'Elbow Touches', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  PTS: {name:'Points', cat: 'SHT', posneg:'POST'},
  PTS_TCH: {name:false},
  PTS_HCCT: {name:false},
  TCH_TOT: {name: 'Touches', cat: 'PSS', posneg: 'POS'},
  FGM: {name:'FG Made',cat: 'SHT', posneg: 'POS'},
  FGA: {name: 'FG Missed', callback: cbs.stdMisses, compare:'FGM', cat: 'SHT', posneg: 'NEG'},
  FG3M: {name:'FG3 Made', cat: 'SHT', posneg: 'POS'},
  FG3A: {name:'FG3 Missed', compare:'FG3M', cat: 'SHT', posneg: 'NEG'},
  FG3_PCT: {name:false},
  EFG_PCT: {name:false},
  PTS_TOT: {name:false},
  REB: {name:false},
  REB_CHANCE: {name:'Rebound Opps Missed',callback: cbs.perGameMisses, compare: 'REB_TOT', cat: 'REB', posneg: 'NEG'},
  REB_COL_PCT: {name:false},
  REB_CONTESTED: {name: 'Contested Rebounds', callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  REB_UNCONTESTED: {name: 'Contested Rebounds', callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  REB_UNCONTESTED_PCT: {name:false},
  REB_TOT: {name:'Rebounds', cat: 'REB', posneg: 'POS'},
  OREB: {name:'Offensive Rebounds', cat: 'REB', posneg: 'POS'},
  OREB_CHANCE: {name:'Offensive Rebound Opps Missed',callback: cbs.perGameMisses, compare: 'OREB', cat: 'REB', posneg: 'NEG'},
  OREB_COL_PCT: {name:false},
  OREB_CONTESTED: {name:'Contested Offensive Rebounds',callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  OREB_UNCONTESTED: {name:'Uncontested Offensive Rebounds',callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  OREB_UNCONTESTED_PCT: {name:false},
  DREB: {name:'Defensive Rebounds', cat: 'REB', posneg: 'POS'},
  DREB_CHANCE: {name:'Defensive Rebound Opps Missed',callback: cbs.perGameMisses, compare: 'DREB', cat: 'REB', posneg: 'NEG'},
  DREB_COL_PCT: {name:false},
  DREB_CONTESTED: {name:'Contested Defensive Rebounds',callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  DREB_UNCONTESTED: {name:'Uncontested Offensive Rebounds',callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  DREB_UNCONTESTED_PCT: {name:false},
  PTS_DRIVE: {name:'Points on Drives', cat: 'SHT', posneg: 'POS', callback: cbs.perGame},
  FGP_DRIVE: {name:false},
  PTS_CLOSE: {name:'Close Shots Points',callback: cbs.perGame,cat:'SHT',posneg:'POS'},
  FGP_CLOSE: {name:false},
  PTS_CATCH_SHOOT: {name:'Catch and Shoot Points',callback: cbs.perGame,cat:'SHT',posneg:'POS'},
  FGP_CATCH_SHOOT: {name:false},
  PTS_PULL_UP: {name:'Pull Up Points',callback: cbs.perGame,cat:'SHT',posneg:'POS'},
  FGP_PULL_UP: {name:false},
  FGA_DRIVE: {name: 'Scoreless Drives', callback: cbs.perGameMissesByScore,compare:'PTS_DRIVE', cat: 'SHT', posneg:'NEG'},
  FGA_CLOSE: {name: 'Scoreless Close Shots', callback: cbs.perGameMissesByScore, compare: 'PTS_CLOSE', cat:'SHT',posneg:'NEG'},
  FGA_CATCH_SHOOT: {name: 'Scoreless Catch and Shoot', callback: cbs.perGameMissesByScore, compare: 'PTS_CATCH_SHOOT', cat:'SHT',posneg:'NEG'},
  FGA_PULL_UP: {name: 'Scoreless Pull Up', callback: cbs.perGameMissesByScore, compare: 'PTS_PULL_UP', cat:'SHT',posneg:'NEG'},
  BLK: {name:false},
  STL: {name:'Steals', cat: 'DEF', posneg:'POS'},
  FGM_DEFEND_RIM: {name:'OPP FG Made at Rim', callback: cbs.perGame, cat: 'DEF', posneg:'NEG'},
  FGA_DEFEND_RIM: {name:'OPP FG Missed at Rim', callback: cbs.perGameMisses, compare:'FGM_DEFEND_RIM',cat:'DEF',posneg:'POS'},
  FGP_DEFEND_RIM: {name:false},
  BLK_TOT: {name:'Blocks', cat: 'DEF', posneg:'POS'},
  DIST: {name:'Miles Traveled', cat:'MSC',posneg:'POS'},
  AV_SPD: {name:false},
  DIST_PG: {name:false},
  DIST_48: {name:false},
  DIST_OFF: {name: 'Miles Traveled Offensive', cat:'MSC',posneg:'POS'},
  DIST_DEF: {name: 'Miles Traveled Defensive', cat:'MSC',posneg:'POS'},
  AV_SPD_OFF: {name:false},
  AV_SPD_DEF: {name:false},
  PLAYER_NAME: {name:false},
  TEAM_ID: {name:false},
  FGM_Restricted_Area: {name:'FG Made Restricted Area', cat:'SHT',posneg:'POS'},
  FGA_Restricted_Area: {name:'FG Missed Restricted Area', callback: cbs.stdMisses, compare:'FGM_Restricted_Area', cat: 'SHT', posneg: 'NEG'},
  FG_PCT_Restricted_Area: {name:false},
  FGM_In_The_Paint_Non_RA: {name:'FG Made In The Paint Non RA', cat:'SHT',posneg:'POS'},
  FGA_In_The_Paint_Non_RA: {name:'FG Missed In The Paint Non RA', callback: cbs.stdMisses, compare:'FGM_In_The_Paint_Non_RA', cat: 'SHT', posneg: 'NEG'},
  FG_PCT_In_The_Paint_Non_RA: {name:false},
  FGM_Mid_Range: {name:'FG Made Mid Range', cat:'SHT',posneg:'POS'},
  FGA_Mid_Range: {name:'FG Missed Mid Range', callback: cbs.stdMisses, compare:'FGM_Mid_Range', cat: 'SHT', posneg: 'NEG'},
  FG_PCT_Mid_Range: {name:false},
  FGM_Left_Corner_3: {name:'Left Corner 3 FG Made', cat: 'SHT', posneg: 'POS'},
  FGA_Left_Corner_3: {name:'Left Corner 3 FG Missed', callback: cbs.stdMisses,compare:'FGM_Left_Corner_3', cat: 'SHT', posneg: 'NEG'},
  FG_PCT_Left_Corner_3: {name:false},
  FGM_Right_Corner_3: {name:'Right Corner 3 FG Made', cat: 'SHT', posneg: 'POS'},
  FGA_Right_Corner_3: {name:'Right Corner 3 FG Missed', callback: cbs.stdMisses,compare:'FGM_Right_Corner_3', cat: 'SHT', posneg: 'NEG'},
  FG_PCT_Right_Corner_3: {name:false},
  FGM_Above_the_Break_3: {name:'FG Made Above the Break', cat:'SHT', posneg:'POS'},
  FGA_Above_the_Break_3: {name:'FG Missed Mid Range', callback: cbs.stdMisses, compare:'FGM_Above_the_Break_3', cat: 'SHT', posneg: 'NEG'},
  FG_PCT_Above_the_Break_3: {name:false},
  FGM_Backcourt: {name:'FG Made Backcourt', cat:'SHT',posneg:'POS'},
  FGA_Backcourt: {name:'FG Missed Backcourt', callback: cbs.stdMisses, compare:'FGM_Backcourt', cat: 'SHT', posneg: 'NEG'},
  FG_PCT_Backcourt: {name:false},
  W: {name:false},
  L: {name:false},
  W_PCT: {name:false},
  FTM: {name:'Freethrows Made', cat:'SHT',posneg:'POS'},
  FTA: {name:'Freethrows Missed', callback: cbs.stdMisses, compare:'FTM', cat: 'SHT', posneg: 'NEG'},
  FT_PCT: {name:false},
  TOV: {name:'Turnovers', cat:'PSS',posneg:'NEG'},
  BLKA: {name:'Shots Blocked', cat: 'SHT',posneg:'NEG'},
  PF: {name:'Personal Fouls', cat:'DEF',posneg:'NEG'},
  PFD: {name:'Personal Fouls Drawn', cat:'MSC', posneg:'POS'},
  PLUS_MINUS: {name:false},
  DD2: {name:false},
  TD3: {name:false},
  CFID: {name:false},
  CFPARAMS: {name:false},
  OPP_FGM_Restricted_Area: {name:'OPP FG Made Restricted Area', cat:'DEF',posneg:'NEG'},
  OPP_FGA_Restricted_Area: {name:'OPP FG Missed Restricted Area', callback: cbs.stdMisses, compare:'OPP_FGM_Restricted_Area', cat: 'DEF', posneg: 'POS'},
  OPP_FG_PCT_Restricted_Area: {name:false},
  OPP_FGM_In_The_Paint_Non_RA: {name:'OPP FG Made In The Paint Non RA', cat:'DEF',posneg:'NEG'},
  OPP_FGA_In_The_Paint_Non_RA: {name:'OPP FG Missed In The Paint Non RA', callback: cbs.stdMisses, compare:'OPP_FGM_In_The_Paint_Non_RA', cat: 'DEF', posneg: 'POS'},
  OPP_FG_PCT_In_The_Paint_Non_RA: {name:false},
  OPP_FGM_Mid_Range: {name:'OPP FG Made Mid Range', cat:'DEF',posneg:'NEG'},
  OPP_FGA_Mid_Range: {name:'OPP FG Missed Mid Range', callback: cbs.stdMisses, compare:'OPP_FGM_Mid_Range', cat: 'DEF', posneg: 'POS'},
  OPP_FG_PCT_Mid_Range: {name:false},
  OPP_FGM_Left_Corner_3: {name:'OPP Left Corner 3 FG Made', cat: 'DEF', posneg: 'NEG'},
  OPP_FGA_Left_Corner_3: {name:'OPP Left Corner 3 FG Missed', callback: cbs.stdMisses, compare:'OPP_FGM_Left_Corner_3', cat: 'DEF', posneg: 'POS'},
  OPP_FG_PCT_Left_Corner_3: {name:false},
  OPP_FGM_Right_Corner_3: {name:'OPP Right Corner 3 FG Made', cat: 'DEF', posneg: 'NEG'},
  OPP_FGA_Right_Corner_3: {name:'OPP Right Corner 3 FG Missed', callback: cbs.stdMisses, compare:'OPP_FGM_Right_Corner_3', cat: 'DEF', posneg: 'POS'},  
  OPP_FG_PCT_Right_Corner_3: {name:false},
  OPP_FGM_Above_the_Break_3: {name:'OPP FG Made Above the Break', cat:'DEF',posneg:'NEG'},
  OPP_FGA_Above_the_Break_3: {name:'OPP FG Missed Above the Break 3', callback: cbs.stdMisses, compare:'OPP_FGM_Restricted_Area', cat: 'DEF', posneg: 'POS'},
  OPP_FG_PCT_Above_the_Break_3: {name:false},
  OPP_FGM_Backcourt: {name:'OPP FG Made Backcourt', cat: 'DEF', posneg: 'NEG'},
  OPP_FGA_Backcourt: {name:'OPP FG Missed Backcourt', callback: cbs.stdMisses, compare:'OPP_FGM_Backcourt', cat: 'DEF', posneg: 'POS'},
  OPP_FG_PCT_Backcourt: {name:false},
};