var cbs = require('./callbacks');

exports.reverseMap = function(){
  var reverseMap = {};
  for (var stat in exports.map){
    var name = exports.map[stat].name || exports.map[stat].keep;
    if (name){
      reverseMap[name] = exports.map[stat];
      reverseMap[name].key = stat;
    }
  }
  return reverseMap;
};
//confusing... name means keep and normalize.  keep means keep but don't normalize
exports.map = {
  Birthdate: {keep:'Birthdate'},
  Position: {keep:'Position'},
  PLAYER_ID: {keep:'PLAYER_ID'},
  PLAYER: {keep: 'Player'},
  FIRST_NAME: {},
  LAST_NAME: {},
  TEAM_ABBREVIATION: {keep: 'Team'},
  GP: {keep:'GP'},
  MIN: {keep: 'MIN'},
  DVS: {},
  DPP: {},
  DTP: {},
  FG_PCT: {},
  PTS_48: {},
  DPP_TOT: {name: 'Points on Drives', cat: 'MSC', posneg:'POS'},
  DVS_TOT: {},
  PASS: {name: 'Passes', callback: cbs.perGame, cat: 'PSS_TM', posneg: 'POS'},
  AST: {},
  AST_FT: {name:'Freethrow Assists', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  AST_SEC: {name:'Secondary Assists', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  AST_POT: {name:'Assist Opportunities', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  PTS_CRT: {name: 'Points Created By Assist', callback: cbs.perGame, cat: 'PSS', posneg: 'POS'},
  PTS_CRT_48: {},
  AST_TOT: {name:'Assists', cat: 'PSS', posneg: 'POS'},
  TCH: {},
  FC_TCH: {name:'Front Court Touches', callback: cbs.perGame, cat: 'PSS_TM', posneg: 'POS'},
  TOP: {},
  CL_TCH: {name:'Close Touches', callback: cbs.perGame, cat: 'PSS_TM', posneg: 'POS'},
  EL_TCH: {name:'Elbow Touches', callback: cbs.perGame, cat: 'PSS_TM', posneg: 'POS'},
  PTS: {name:'Points', cat: 'SHT_TM', posneg:'POS'},
  PTS_TCH: {},
  PTS_HCCT: {},
  TCH_TOT: {name: 'Touches', cat: 'PSS_TM', posneg: 'POS'},
  FGM: {name:'FG Made',cat: 'SHT', posneg: 'POS', coupledName: 'FG Efficiency'},
  FGA: {name: 'FG Missed', callback: cbs.stdMisses, compare:'FGM', cat: 'SHT', posneg: 'NEG', coupledName: 'FG Efficiency'},
  FG3M: {name:'FG3 Made', cat: 'SHT', posneg: 'POS', coupledName: 'FG3 Efficiency'},
  FG3A: {name:'FG3 Missed', callback: cbs.stdMisses, compare:'FG3M', cat: 'SHT', posneg: 'NEG', coupledName: 'FG3 Efficiency'},
  FG3_PCT: {},
  EFG_PCT: {},
  PTS_TOT: {},
  REB: {},
  REB_CHANCE: {name:'Rebound Opps Missed',callback: cbs.perGameMisses, compare: 'REB_TOT', cat: 'REB', posneg: 'NEG', coupledName: 'Rebounding Efficiency'},
  REB_COL_PCT: {},
  REB_CONTESTED: {name: 'Contested Rebounds', callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  REB_UNCONTESTED: {name: 'Contested Rebounds', callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  REB_UNCONTESTED_PCT: {},
  REB_TOT: {name:'Rebounds', cat: 'REB', posneg: 'POS', coupledName: 'Rebounding Efficiency'},
  OREB: {name:'Offensive Rebounds', cat: 'REB', posneg: 'POS', coupledName: 'Offensive Rebounding Efficiency'},
  OREB_CHANCE: {name:'Offensive Rebound Opps Missed',callback: cbs.perGameMisses, compare: 'OREB', cat: 'REB', posneg: 'NEG', coupledName: 'Offensive Rebounding Efficiency'},
  OREB_COL_PCT: {},
  OREB_CONTESTED: {name:'Contested Offensive Rebounds',callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  OREB_UNCONTESTED: {name:'Uncontested Offensive Rebounds',callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  OREB_UNCONTESTED_PCT: {},
  DREB: {name:'Defensive Rebounds', cat: 'REB', posneg: 'POS', coupledName: 'Defensive Rebounding Efficiency'},
  DREB_CHANCE: {name:'Defensive Rebound Opps Missed',callback: cbs.perGameMisses, compare: 'DREB', cat: 'REB', posneg: 'NEG', coupledName: 'Defensive Rebounding Efficiency'},
  DREB_COL_PCT: {},
  DREB_CONTESTED: {name:'Contested Defensive Rebounds',callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  DREB_UNCONTESTED: {name:'Uncontested Offensive Rebounds',callback: cbs.perGame, cat: 'REB', posneg: 'POS'},
  DREB_UNCONTESTED_PCT: {},
  PTS_DRIVE: {name:'Points on Drives', cat: 'SHT', posneg: 'POS', callback: cbs.perGame, coupledName: 'Drive Efficiency'},
  FGP_DRIVE: {},
  PTS_CLOSE: {name:'Close Shots Points',callback: cbs.perGame,cat:'SHT',posneg:'POS', coupledName: 'Close Shot Efficiency'},
  FGP_CLOSE: {},
  PTS_CATCH_SHOOT: {name:'Catch and Shoot Points',callback: cbs.perGame,cat:'SHT',posneg:'POS', coupledName: 'Catch and Shoot Efficiency'},
  FGP_CATCH_SHOOT: {},
  PTS_PULL_UP: {name:'Pull Up Points',callback: cbs.perGame,cat:'SHT',posneg:'POS', coupledName: 'Pull Up Efficiency'},
  FGP_PULL_UP: {},
  FGA_DRIVE: {name: 'Scoreless Drives', callback: cbs.perGameMissesByScore,compare:'PTS_DRIVE', cat: 'SHT', posneg:'NEG', coupledName: 'Drive Efficiency'},
  FGA_CLOSE: {name: 'Scoreless Close Shots', callback: cbs.perGameMissesByScore, compare: 'PTS_CLOSE', cat:'SHT',posneg:'NEG', coupledName: 'Close Shot Efficiency'},
  FGA_CATCH_SHOOT: {name: 'Scoreless Catch and Shoot', callback: cbs.perGameMissesByScore, compare: 'PTS_CATCH_SHOOT', cat:'SHT',posneg:'NEG', coupledName: 'Catch and Shoot Efficiency'},
  FGA_PULL_UP: {name: 'Scoreless Pull Up', callback: cbs.perGameMissesByScore, compare: 'PTS_PULL_UP', cat:'SHT',posneg:'NEG', coupledName: 'Pull Up Efficiency'},
  BLK: {},
  STL: {name:'Steals', cat: 'DEF', posneg:'POS'},
  FGM_DEFEND_RIM: {name:'OPP FG Made at Rim', callback: cbs.perGame, cat: 'DEF', posneg:'NEG'},
  FGA_DEFEND_RIM: {name:'OPP FG Missed at Rim', callback: cbs.perGameMisses, compare:'FGM_DEFEND_RIM',cat:'DEF',posneg:'POS'},
  FGP_DEFEND_RIM: {},
  BLK_TOT: {name:'Blocks', cat: 'DEF', posneg:'POS'},
  DIST: {name:'Miles Traveled', cat:'MSC',posneg:'POS'},
  AV_SPD: {},
  DIST_PG: {},
  DIST_48: {},
  DIST_OFF: {name: 'Miles Traveled Offensive', cat:'MSC',posneg:'POS'},
  DIST_DEF: {name: 'Miles Traveled Defensive', cat:'MSC',posneg:'POS'},
  AV_SPD_OFF: {},
  AV_SPD_DEF: {},
  PLAYER_NAME: {},
  TEAM_ID: {},
  // FGM_Restricted_Area: {name:'FG Made Restricted Area', cat:'SHT',posneg:'POS',team:true},
  // FGA_Restricted_Area: {name:'FG Missed Restricted Area', callback: cbs.stdMisses, compare:'FGM_Restricted_Area', cat: 'SHT', posneg: 'NEG',team:true},
  // FG_PCT_Restricted_Area: {},
  // FGM_In_The_Paint_Non_RA: {name:'FG Made In The Paint Non RA', cat:'SHT',posneg:'POS',team:true},
  // FGA_In_The_Paint_Non_RA: {name:'FG Missed In The Paint Non RA', callback: cbs.stdMisses, compare:'FGM_In_The_Paint_Non_RA', cat: 'SHT', posneg: 'NEG',team:true},
  // FG_PCT_In_The_Paint_Non_RA: {},
  // FGM_Mid_Range: {name:'FG Made Mid Range', cat:'SHT',posneg:'POS',team:true},
  // FGA_Mid_Range: {name:'FG Missed Mid Range', callback: cbs.stdMisses, compare:'FGM_Mid_Range', cat: 'SHT', posneg: 'NEG',team:true},
  // FG_PCT_Mid_Range: {},
  // FGM_Left_Corner_3: {name:'Left Corner 3 FG Made', cat: 'SHT', posneg: 'POS',team:true},
  // FGA_Left_Corner_3: {name:'Left Corner 3 FG Missed', callback: cbs.stdMisses,compare:'FGM_Left_Corner_3', cat: 'SHT', posneg: 'NEG',team:true},
  // FG_PCT_Left_Corner_3: {},
  // FGM_Right_Corner_3: {name:'Right Corner 3 FG Made', cat: 'SHT', posneg: 'POS',team:true},
  // FGA_Right_Corner_3: {name:'Right Corner 3 FG Missed', callback: cbs.stdMisses,compare:'FGM_Right_Corner_3', cat: 'SHT', posneg: 'NEG',team:true},
  // FG_PCT_Right_Corner_3: {},
  // FGM_Above_the_Break_3: {name:'FG Made Above the Break', cat:'SHT', posneg:'POS',team:true},
  // FGA_Above_the_Break_3: {name:'FG Missed Mid Range', callback: cbs.stdMisses, compare:'FGM_Above_the_Break_3', cat: 'SHT', posneg: 'NEG',team:true},
  // FG_PCT_Above_the_Break_3: {},
  // FGM_Backcourt: {name:'FG Made Backcourt', cat:'SHT',posneg:'POS',team:true},
  // FGA_Backcourt: {name:'FG Missed Backcourt', callback: cbs.stdMisses, compare:'FGM_Backcourt', cat: 'SHT', posneg: 'NEG',team:true},
  // FG_PCT_Backcourt: {},
  W: {},
  L: {},
  W_PCT: {},
  FTM: {name:'Freethrows Made', cat:'SHT',posneg:'POS', coupledName: 'Freethrow Efficiency'},
  FTA: {name:'Freethrows Missed', callback: cbs.stdMisses, compare:'FTM', cat: 'SHT', posneg: 'NEG', coupledName: 'Freethrow Efficiency'},
  FT_PCT: {},
  TOV: {name:'Turnovers', cat:'PSS',posneg:'NEG'},
  BLKA: {name:'Shots Blocked', cat: 'SHT',posneg:'NEG'},
  PF: {name:'Personal Fouls', cat:'DEF',posneg:'NEG'},
  PFD: {name:'Personal Fouls Drawn', cat:'MSC', posneg:'POS'},
  PLUS_MINUS: {},
  DD2: {},
  TD3: {},
  CFID: {},
  CFPARAMS: {},
  OPP_FGM_Restricted_Area: {name:'OPP FG Made Restricted Area', cat:'DEF',posneg:'NEG',team:true},
  OPP_FGA_Restricted_Area: {name:'OPP FG Missed Restricted Area', callback: cbs.stdMisses, compare:'OPP_FGM_Restricted_Area', cat: 'DEF', posneg: 'POS',team:true},
  OPP_FG_PCT_Restricted_Area: {},
  OPP_FGM_In_The_Paint_Non_RA: {name:'OPP FG Made In The Paint Non RA', cat:'DEF',posneg:'NEG',team:true},
  OPP_FGA_In_The_Paint_Non_RA: {name:'OPP FG Missed In The Paint Non RA', callback: cbs.stdMisses, compare:'OPP_FGM_In_The_Paint_Non_RA', cat: 'DEF', posneg: 'POS',team:true},
  OPP_FG_PCT_In_The_Paint_Non_RA: {},
  OPP_FGM_Mid_Range: {name:'OPP FG Made Mid Range', cat:'DEF',posneg:'NEG',team:true},
  OPP_FGA_Mid_Range: {name:'OPP FG Missed Mid Range', callback: cbs.stdMisses, compare:'OPP_FGM_Mid_Range', cat: 'DEF', posneg: 'POS',team:true},
  OPP_FG_PCT_Mid_Range: {},
  OPP_FGM_Left_Corner_3: {name:'OPP Left Corner 3 FG Made', cat: 'DEF', posneg: 'NEG',team:true},
  OPP_FGA_Left_Corner_3: {name:'OPP Left Corner 3 FG Missed', callback: cbs.stdMisses, compare:'OPP_FGM_Left_Corner_3', cat: 'DEF', posneg: 'POS',team:true},
  OPP_FG_PCT_Left_Corner_3: {},
  OPP_FGM_Right_Corner_3: {name:'OPP Right Corner 3 FG Made', cat: 'DEF', posneg: 'NEG',team:true},
  OPP_FGA_Right_Corner_3: {name:'OPP Right Corner 3 FG Missed', callback: cbs.stdMisses, compare:'OPP_FGM_Right_Corner_3', cat: 'DEF', posneg: 'POS',team:true},  
  OPP_FG_PCT_Right_Corner_3: {},
  OPP_FGM_Above_the_Break_3: {name:'OPP FG Made Above the Break', cat:'DEF',posneg:'NEG',team:true},
  OPP_FGA_Above_the_Break_3: {name:'OPP FG Missed Above the Break 3', callback: cbs.stdMisses, compare:'OPP_FGM_Above_the_Break_3', cat: 'DEF', posneg: 'POS',team:true},
  OPP_FG_PCT_Above_the_Break_3: {},
  OPP_FGM_Backcourt: {name:'OPP FG Made Backcourt', cat: 'DEF', posneg: 'NEG',team:true},
  OPP_FGA_Backcourt: {name:'OPP FG Missed Backcourt', callback: cbs.stdMisses, compare:'OPP_FGM_Backcourt', cat: 'DEF', posneg: 'POS',team:true},
  OPP_FG_PCT_Backcourt: {},
};