var mongoose = require('mongoose'),
    config = require('../../config/config');

mongoose.model('Player', new mongoose.Schema({
      "Player": String,
      "Team": String,
      "GP": Number,
      "MIN per game": Number,
      "STL per game": Number,
      "BLK per game": Number,
      "Total BLK": Number,
      "Opp FGM at Rim per game": Number,
      "Opp FGA at Rim per game": Number,
      "Opp FGP at Rim": Number,
      "Catch and Shoot Total PTS": Number,
      "Catch and Shoot PTS per game": Number,
      "Catch and Shoot FGM per game": Number,
      "Catch and Shoot FGA per game": Number,
      "Catch and Shoot FG%": Number,
      "Catch and Shoot 3FGM per game": Number,
      "Catch and Shoot 3FGA per game": Number,
      "Catch and Shoot 3FG%": Number,
      "Catch and Shoot eFG%": Number,
      "REB per game": Number,
      "Percentage of rebounds per chance": Number,
      "REB Chances per game": Number,
      "Total REB": Number,
      "Contested REB per game": Number,
      "Uncontested REB per game": Number,
      "Contested REB Percentage": Number,
      "Distance Traveled (total miles)": Number,
      "Average Speed (mph)": Number,
      "Distance Traveled Per Game (miles)": Number,
      "Distance Traveled Per 48 Minutes (miles)": Number,
      "Pull Up Shots MIN per game": Number,
      "Pull Up Shots Total PTS": Number,
      "Pull Up Shots PTS per game": Number,
      "Pull Up Shots FGM per game": Number,
      "Pull Up Shots FGA per game": Number,
      "Pull Up Shots FG_PCT": Number,
      "Pull Up Shots FG3M per game": Number,
      "Pull Up Shots FG3A per game": Number,
      "Pull Up Shots FG3_PCT": Number,
      "Pull Up Shots EFG_PCT": Number,
      "PTS per game": Number,
      "Drives PTS per game": Number,
      "Drives FG%": Number,
      "Close Shots PTS per game": Number,
      "Close Shots FG%": Number,
      "eFG%": Number,
      "FG% on Drives": Number,
      "Total Drives": Number,
      "Total Player PTS on Drives": Number,
      "Drives Per Game": Number,
      "Player PPG on Drives": Number,
      "Team PPG on Drives": Number,
      "PTS Per 48 Min on Drives": Number,
      "AST per game": Number,
      "Passes per game": Number,
      "Assists per game": Number,
      "FT Assists per game": Number,
      "Secondary Assists per game": Number,
      "Assist opportunities per game": Number,
      "Points created by assist per game": Number,
      "Points Created by AST Per 48 Min": Number,
      "Touches per game": Number,
      "Total Touches": Number,
      "Front Court Touches per game": Number,
      "Time of Possession (min)": Number,
      "Close Touches per game": Number,
      "Elbow Touches per game": Number,
      "PTS Per Touch": Number,
      "PTS Per Half Court Touch": Number
    },{collection: 'players'}));
